Full App
mutinhiri/book-an-appointment-frontend pull request #11
Opened 2022-04-08 21:03 UTC by mutinhiri

In this Pr we added changes for the full app to work properly

2022-04-08 21:44 UTC, MuriloRoque requested changes
Hi @mutinhiri, @Emmy-github-webdev,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:

- [ ] Add tests for your app, it's very important.

## Highlights 

- Very nice and clean code.
- Professional repository.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-08 21:44 UTC, MuriloRoque commented on src/Home.js
> +          {/* <Route path="/appointment-form" element={<AppointmentForm />} /> */}
- [ ] Remove this commented code if you won't use it.

2022-04-13 11:26 UTC, christianotieno requested changes
Hi @mutinhiri & @Emmy-github-webdev, ✋🏾  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-13 11:26 UTC, christianotieno commented on src/api/BaseURL.js
> +// const Development = 'http://127.0.0.1:8080/api/v1/';
Do we need this here? 🤔

2022-04-13 11:26 UTC, christianotieno commented on src/components/AddItem/AddItem.js
> +/* eslint-disable react/jsx-props-no-spreading */
Why are we disbaling eslint for props spreading? 🤔

2022-04-13 11:26 UTC, christianotieno commented on src/components/appointments/Appointments.js
> +/* eslint-disable react/no-array-index-key */
Same case here for array index. I am sure there is a workaround. What do you think?

2022-04-13 12:54 UTC, MuriloRoque approved these changes
Hi @mutinhiri, @Emmy-github-webdev,

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-04-13 14:32 UTC, merged